export const RECEIVE_NONPROFIT_ITEMS = 'RECEIVE_NONPROFIT_ITEMS';
export const RECEIVE_NONPROFIT_ITEM = 'RECEIVE_NONPROFIT_ITEM';
export const DELETE_NONPROFIT_ITEM = 'DELETE_NONPROFIT_ITEM';
export const RECEIVE_CART = 'receive_cart';
